name: guettgui
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices.
  flutter_lints: ^6.0.0

flutter:
  # Ensures that the Material Icons font is included.
  uses-material-design: true

  # Add assets to your application.
  assets:
    - assets/images/logoColor.jpg

  # Uncomment below to add custom fonts later if needed.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  # Additional font configurations can go here.